name: ğŸš€ CI/CD workflow

on:
  push:
    branches:
      - develop
      - feat/*
      - Feat/*
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      TEST_FAILED: ${{ steps.set-test-failed.outputs.TEST_FAILED }}
    
    steps:
    - name: ğŸ§‘â€ğŸ’» Checkout Repository
      uses: actions/checkout@v4

    - name: ğŸ”§ Set Up .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - name: ğŸ” Trust ASP.NET Core Developer Certificate
      run: dotnet dev-certs https --trust

    - name: ğŸ“¦ Restore Dependencies
      run: dotnet restore

    - name: ğŸ—ï¸ Build Project
      run: dotnet build --configuration Release
        
    - name: ğŸ§ª Run All Tests
      id: set-test-failed
      run: |
        TEST_FAILED=0
        for proj in $(find test -name "*.csproj"); do
          proj_name=$(basename $proj .csproj)
          if ! dotnet test "$proj" --configuration Release --logger "trx;LogFileName=${proj_name}.trx" --results-directory ./test-results; then
            TEST_FAILED=1
          fi
        done
        echo "TEST_FAILED=$TEST_FAILED" >> $GITHUB_ENV
        echo "TEST_FAILED=$TEST_FAILED" >> $GITHUB_OUTPUT
      shell: bash

    - name: ğŸ”„ Convert Test Results to JUnit Format
      if: github.event_name == 'pull_request'
      run: |
        dotnet tool install --global trx2junit
        find ./test-results -name '*.trx' -exec trx2junit {} \;

    - name: ğŸ“‘ Publish Test Results as PR Comment
      if: github.event_name == 'pull_request'
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: '**/test-results/*.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: âœ… Add Check Comments for Failed Code Lines
      if: github.event_name == 'pull_request'
      uses: mikepenz/action-junit-report@v3
      with:
        report_paths: '**/test-results/*.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: ğŸ“¦ Publish Project
      if: ${{ needs.build.outputs.TEST_FAILED == '0' && github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
      run: dotnet publish --configuration Release --output ./publish

    - name: ğŸ“¤ Upload Published Artifact
      if: ${{ needs.build.outputs.TEST_FAILED == '0' && github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./publish

  download-artifact:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.TEST_FAILED == '0' && github.event_name == 'push' && github.ref == 'refs/heads/develop' }}

    steps:
    - name: â¬‡ï¸ Download Published Artifact
      uses: actions/download-artifact@v4
      with:
        name: published-app
        path: ./downloaded-publish
